SELECT SELO, RETORNO, STATUS, JSON
FROM selados
WHERE (STATUS IS NULL OR STATUS != 'SUCESSO')
    AND DATE(STR_TO_DATE(DATAENVIO, '%Y-%m-%d %H:%i:%s')) BETWEEN '2026-03-01' AND '2026-03-30'
ORDER BY STR_TO_DATE(DATAENVIO, '%Y-%m-%d %H:%i:%s')
LIMIT 1000;
