-- ===============================================================
-- Tabela de Log de Auditoria para Parametros
-- Registrar todas as alterações na tabela parametros
-- ===============================================================

CREATE TABLE IF NOT EXISTS log_parametros (
    id bigint generated by default as identity primary key,
    codigo_parametro integer not null,              -- CODIGO_PAR original
    
    -- Informações do campo alterado
    nome_campo varchar(50) not null,                -- Nome do campo alterado
    valor_anterior text,                            -- Valor anterior (texto para qualquer tipo)
    valor_novo text,                                -- Novo valor
    
    -- Metadata da alteração
    tipo_operacao varchar(10) not null,            -- INSERT, UPDATE, DELETE
    data_alteracao timestamp default current_timestamp,
    usuario_alteracao varchar(50),                 -- Usuário que fez a alteração
    ip_origem varchar(45),                          -- IP de origem
    
    -- Contexto adicional
    modulo_origem varchar(50),                     -- NFSe, Protesto, Selos, etc.
    observacao varchar(500)                         -- Observação livre
);

-- Índice para consultas
CREATE INDEX idx_log_parametros_codigo ON log_parametros(codigo_parametro);
CREATE INDEX idx_log_parametros_data ON log_parametros(data_alteracao);
CREATE INDEX idx_log_parametros_usuario ON log_parametros(usuario_alteracao);

COMMENT ON TABLE log_parametros IS 'Log de auditoria das alterações na tabela parametros';