-- ===============================================================
-- Tabela de Parametrização de Impostos sobre Serviços (NFSe)
-- Considera a Reforma Tributária (EC 132/2023)
-- 
-- Cronograma de Implementação:
-- - 2025-2026: Implementação gradual CBS/IBS
-- - 2026: Início substituição ISS
-- - 2033: Substituição completa ISS por CBS+IBS
-- ===============================================================

-- drop table if exists nfse_impostos cascade;
-- drop sequence if exists nfse_impostos_id_seq;

create table nfse_impostos (
    id bigint generated by default as identity primary key,
    codigo varchar(20) not null unique,           -- Código do imposto
    nome varchar(100) not null,                   -- Nome completo
    nome_abreviado varchar(50),                    -- Nome abreviado
    
    -- Tipo de Imposto
    tipo_imposto varchar(30) not null,             -- ISS, CBS, IBS, PIS, COFINS, CSLL, IRPJ, CPP
    abrangencia varchar(20) not null,              -- MUNICIPAL, ESTADUAL, FEDERAL, NACIONAL
    
    -- Vigência (Cronograma Reforma Tributária)
    data_inicio date not null,                     -- Data início vigência
    data_fim date,                                 -- Data fim vigência (pode ser null = vigente)
    ativo boolean default true,                    -- Se está ativo
    
    -- Alíquotas
    aliquota numeric(5,4) not null,               -- Alíquota (ex: 0.05 = 5%)
    aliquota_minima numeric(5,4),                  -- Alíquota mínima (para cálculo)
    aliquota_maxima numeric(5,4),                  -- Alíquota máxima (para cálculo)
    
    -- Base de Cálculo
    base_calculo varchar(20) default 'VALOR_SERVICO',  -- VALOR_SERVICO, VALOR_SERVICO_DESC, etc.
    percentual_base numeric(5,4) default 1.0,    -- Percentual da base de cálculo
    
    -- Configuração por Município (IBGE)
    codigo_ibge varchar(7),                       -- Código IBGE do município (null = todos)
    
    -- Cálculo
    calcula_iss boolean default true,              -- Se entra no cálculo do ISS
    calcula_cbs boolean default false,            -- Se entra no cálculo da CBS
    calcula_ibs boolean default false,            -- Se entra no cálculo do IBS
    calcula_pis boolean default false,            -- Se entra no cálculo do PIS
    calcula_cofins boolean default false,         -- Se entra no cálculo do COFINS
    calcula_csll boolean default false,           -- Se entra no cálculo do CSLL
    calcula_irpj boolean default false,          -- Se entra no cálculo do IRPJ
    calcula_cpp boolean default false,            -- Se entra no cálculo do CPP
    
    -- Ordem no cálculo (para display/fatura)
    ordem_calculo integer default 0,              -- Ordem de apresentação
    
    -- Natureza da operação
    natureza_operacao varchar(50),                 -- Tributação, Isento, Não Tributado, etc.
    
    -- Observações
    observacoes text,
    
    -- Controle
    codigo_usu integer,                           -- Usuário criação
    dtcadastro timestamp default current_timestamp,
    dtalteracao timestamp default current_timestamp,
    
    constraint chk_aliquota check (aliquota >= 0 and aliquota <= 1),
    constraint chk_tipo_imposto check (tipo_imposto in ('ISS', 'CBS', 'IBS', 'PIS', 'COFINS', 'CSLL', 'IRPJ', 'CPP'))
);

comment on table nfse_impostos is 'Tabela de parametrização de impostos sobre serviços NFS-e';
comment on column nfse_impostos.tipo_imposto is 'Tipo de imposto: ISS (atual), CBS (Reforma -取代ISS), IBS (Reforma -取代ISS), PIS, COFINS, CSLL, IRPJ, CPP (nova)';
comment on column nfse_impostos.abrangencia is 'Abrangência: MUNICIPAL (ISS), ESTADUAL (ICMS), FEDERAL (IR, PIS, COFINS, CSLL), NACIONAL (CBS, IBS)';
comment on column nfse_impostos.base_calculo is 'Base de cálculo: VALOR_SERVICO, VALOR_SERVICO_DESC, VALOR_LIQUIDO';
comment on column nfse_impostos.natureza_operacao is 'TRIBUTACAO, ISENTO, NAO_TRIBUTADO, SUSPENSAO, IMPOSTO_RETIDO';

-- ===============================================================
-- Tabela de Parâmetros por Município (IBGE)
-- ===============================================================

-- drop table if exists nfse_impostos_municipio cascade;

create table nfse_impostos_municipio (
    id bigint generated by default as identity primary key,
    municipio_id bigint not null,                 -- FK para município
    
    -- CBS (Contribuição sobre Bens e Serviços) - Federal
    cbs_aliquota numeric(5,4) default 0.10,       -- Padrão: 10%
    cbs_valor_deduzir numeric(15,2),             -- Valor a deduzir (se houver)
    cbs_ativo boolean default false,             -- Se CBS já está ativa
    
    -- IBS (Imposto sobre Bens e Serviços) - Estadual/Municipal
    ibs_aliquota numeric(5,4) default 0.10,       -- Padrão: 10%
    ibs_valor_deduzir numeric(15,2),
    ibs_ativo boolean default false,
    
    -- ISS (Transição - até 2033)
    iss_aliquota numeric(5,4) default 0.05,       -- Padrão: 5% (varia por município)
    iss_aliquota_min numeric(5,4) default 0.02,  -- Mínimo: 2%
    iss_aliquota_max numeric(5,4) default 0.05,  -- Máximo: 5%
    
    -- PIS/COFINS (Serviços)
    pis_aliquota numeric(5,4) default 0.0165,    -- Padrão: 1,65%
    cofins_aliquota numeric(5,4) default 0.076,   -- Padrão: 7,6%
    
    -- CSLL (Contribuição Social sobre Lucro)
    csll_aliquota numeric(5,4) default 0.09,     -- Padrão: 9%
    
    -- IRPJ (Imposto de Renda)
    irpj_aliquota numeric(5,4) default 0.15,     -- Padrão: 15%
    irpj_adicional numeric(5,4) default 0.025,  -- Adicional: 2,5%
    
    -- CPP (Contribuição Patronal) - Nova na Reforma
    cpp_aliquota numeric(5,4) default 0.12,      -- Padrão: 12% (a definir)
    cpp_ativo boolean default false,
    
    -- Fase de transição
    fase_transicao varchar(20) default 'NAO_INICIADA',  -- NAO_INICIADA, TRANSICAO, PLENA
    data_inicio_transicao date,
    data_fim_transicao date,
    
    -- Controle
    codigo_usu integer,
    dtcadastro timestamp default current_timestamp,
    dtalteracao timestamp default current_timestamp,
    
    constraint unique_municipio unique (municipio_id)
);

comment on table nfse_impostos_municipio is 'Parâmetros de impostos por município (IBGE)';
comment on column nfse_impostos_municipio.fase_transicao is 'Fase da transição tributária: NAO_INICIADA, TRANSICAO, PLENA';

-- ===============================================================
-- Tabela de Configuração de Serviços (LC 116/2003 + CBS/IBS)
-- ===============================================================

-- drop table if exists nfse_servicos_impostos cascade;

create table nfse_servicos_impostos (
    id bigint generated by default as identity primary key,
    codigo_servico varchar(10) not null,          -- Código do serviço (LC 116)
    descricao varchar(500),                       -- Descrição
    
    -- Impostos aplicáveis (podem ser múltiplos na reforma)
    iss_aplicavel boolean default true,           -- Se ISS se aplica
    cbs_aplicavel boolean default false,          -- Se CBS se aplica (pós-reforma)
    ibs_aplicavel boolean default false,          -- Se IBS se aplica (pós-reforma)
    pis_aplicavel boolean default false,         -- Se PIS se aplica
    cofins_aplicavel boolean default false,      -- Se COFINS se aplica
    csll_aplicavel boolean default false,        -- Se CSLL se aplica
    irpj_aplicavel boolean default false,        -- Se IRPJ se aplica
    cpp_aplicavel boolean default false,         -- Se CPP se aplica
    
    -- Alíquotas específicas (override do padrão)
    iss_aliquota numeric(5,4),
    cbs_aliquota numeric(5,4),
    ibs_aliquota numeric(5,4),
    
    -- Categoria do serviço (para regime)
    categoria_servico varchar(30),               -- SIMPLES, RETIDO, NORMAL
    natureza_receita varchar(30),                 -- SERVICOS, OBRAS, LOCACAO
    
    -- Ativo
    ativo boolean default true,
    
    -- Controle
    codigo_usu integer,
    dtcadastro timestamp default current_timestamp,
    dtalteracao timestamp default current_timestamp
);

comment on table nfse_servicos_impostos is 'Relação entre códigos de serviço e impostos aplicáveis';

-- ===============================================================
-- Dados Iniciais - Impostos Nacionais (Referência)
-- ===============================================================

-- INSERT INTO nfse_impostos (codigo, nome, nome_abreviado, tipo_imposto, abrangencia, data_inicio, aliquota, calcula_iss, ordem_calculo, natureza_operacao) values
-- ('ISS', 'Imposto Sobre Serviços', 'ISS', 'ISS', 'MUNICIPAL', '2004-01-01', 0.05, true, 1, 'TRIBUTACAO'),
-- ('PIS', 'Programa de Integração Social', 'PIS', 'PIS', 'FEDERAL', '2002-01-01', 0.0165, false, 2, 'TRIBUTACAO'),
-- ('COFINS', 'Contribuição para o Financiamento da Seguridade Social', 'COFINS', 'COFINS', 'FEDERAL', '2002-01-01', 0.076, false, 3, 'TRIBUTACAO'),
-- ('CSLL', 'Contribuição Social sobre o Lucro Líquido', 'CSLL', 'CSLL', 'FEDERAL', '2002-01-01', 0.09, false, 4, 'TRIBUTACAO'),
-- ('IRPJ', 'Imposto de Renda de Pessoa Jurídica', 'IRPJ', 'IRPJ', 'FEDERAL', '2002-01-01', 0.15, false, 5, 'TRIBUTACAO'),
-- ('CBS', 'Contribuição sobre Bens e Serviços', 'CBS', 'CBS', 'NACIONAL', '2026-04-01', 0.10, false, 6, 'TRIBUTACAO'),
-- ('IBS', 'Imposto sobre Bens e Serviços', 'IBS', 'IBS', 'NACIONAL', '2026-04-01', 0.10, false, 7, 'TRIBUTACAO'),
-- ('CPP', 'Contribuição Patronal', 'CPP', 'CPP', 'NACIONAL', '2026-04-01', 0.12, false, 8, 'TRIBUTACAO');

-- ===============================================================
-- Índices para Performance
-- ===============================================================

create index idx_nfse_impostos_tipo on nfse_impostos(tipo_imposto);
create index idx_nfse_impostos_ibge on nfse_impostos(codigo_ibge);
create index idx_nfse_impostos_ativo on nfse_impostos(ativo);
create index idx_nfse_impostos_data on nfse_impostos(data_inicio, data_fim);
create index idx_nfse_impostos_municipio on nfse_impostos_municipio(municipio_id);

-- ===============================================================
-- Verificar estrutura
-- ===============================================================

-- select * from nfse_impostos order by ordem_calculo;
-- select column_name, data_type from information_schema.columns where table_name = 'nfse_impostos';